# Generated by Django 5.1 on 2024-08-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragabiuser',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fragabiuser',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
